# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: hoatzin 0.2.2 ruby lib

Gem::Specification.new do |s|
  s.name = "hoatzin"
  s.version = "0.2.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["robl"]
  s.date = "2014-05-29"
  s.description = "Hoatzin is a text classifier in Ruby that uses SVM for it's classification."
  s.email = "robl@rjlee.net"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.markdown"
  ]
  s.files = [
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.markdown",
    "Rakefile",
    "VERSION",
    "hoatzin.gemspec",
    "lib/classifier.rb",
    "lib/feature_vector/builder.rb",
    "lib/feature_vector/model.rb",
    "lib/hoatzin.rb",
    "lib/parser.rb",
    "lib/string.rb",
    "test/helper.rb",
    "test/models/readonly-test/metadata",
    "test/models/readonly-test/model",
    "test/models/test/metadata",
    "test/models/test/model",
    "test/test_hoatzin.rb"
  ]
  s.homepage = "http://github.com/rjlee/hoatzin"
  s.licenses = ["MIT"]
  s.rubygems_version = "2.2.2"
  s.summary = "SVM Classifier in Ruby"

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<libsvm-ruby-swig>, [">= 0"])
      s.add_runtime_dependency(%q<ruby-stemmer>, [">= 0"])
      s.add_runtime_dependency(%q<gtokenizer>, [">= 0"])
      s.add_runtime_dependency(%q<iconv>, [">= 0"])
      s.add_development_dependency(%q<minitest>, [">= 0"])
      s.add_development_dependency(%q<shoulda>, [">= 0"])
      s.add_development_dependency(%q<bundler>, [">= 0"])
      s.add_development_dependency(%q<jeweler>, [">= 0"])
      s.add_development_dependency(%q<simplecov>, ["~> 0.7.1"])
    else
      s.add_dependency(%q<libsvm-ruby-swig>, [">= 0"])
      s.add_dependency(%q<ruby-stemmer>, [">= 0"])
      s.add_dependency(%q<gtokenizer>, [">= 0"])
      s.add_dependency(%q<iconv>, [">= 0"])
      s.add_dependency(%q<minitest>, [">= 0"])
      s.add_dependency(%q<shoulda>, [">= 0"])
      s.add_dependency(%q<bundler>, [">= 0"])
      s.add_dependency(%q<jeweler>, [">= 0"])
      s.add_dependency(%q<simplecov>, ["~> 0.7.1"])
    end
  else
    s.add_dependency(%q<libsvm-ruby-swig>, [">= 0"])
    s.add_dependency(%q<ruby-stemmer>, [">= 0"])
    s.add_dependency(%q<gtokenizer>, [">= 0"])
    s.add_dependency(%q<iconv>, [">= 0"])
    s.add_dependency(%q<minitest>, [">= 0"])
    s.add_dependency(%q<shoulda>, [">= 0"])
    s.add_dependency(%q<bundler>, [">= 0"])
    s.add_dependency(%q<jeweler>, [">= 0"])
    s.add_dependency(%q<simplecov>, ["~> 0.7.1"])
  end
end

