require 'svm'
require 'lingua/stemmer'
require 'iconv'
require 'pp'

require 'hoatzin/string'
require 'hoatzin/classifier'
require 'hoatzin/parser'
require 'feature_vector/model'
require 'feature_vector/builder'
